# I. Overview:

* This ipython notebook utilizes the __batch_alerts module__ to generate near real time alerts for feeder level outages
* Inputs:
    * Daily raw data (edna, ami, scada) from FPL (in csv form)
    * Meta data on the feeders (for ami anomaly transformation)
    * Congiguration files
    * pkl clf model
* Outputs:
    * dictionary of alerter:
        * key = feeder
        * value = alerter (collection of alerts) of a feeder

# II. Libraries:

In [1]:
from autogrid.pam.anomaly import anomaly
from autogrid.pam.alert import alert 
from autogrid.pam.batch_alerts.batch_alerts import BatchAlerts

import cPickle as pickle
import pandas as pd

# III. Functions:

In [2]:
# function #1:
def combine_preds_df(alerts_dict):
    '''
    PURPOSE:
        - combine prediction table of different fdrs into one df
    INPUT:
        - alerts_dict (dict; keys: fdr id; values; alerter object)
    OUTPUT:
        - preds_df (df of combined preds with sigantures)
    '''
    first = True
    for fdr in alerts_dict.keys():
        if alerts_dict[fdr].preds.empty:
            continue
        else:
            loc_preds_table = alerts_dict[fdr].preds
            loc_preds_table = pd.concat([loc_preds_table, alerts_dict[fdr].X], axis=1)            
        if first:
            preds_table = loc_preds_table
            first = False
        else:
            preds_table = pd.concat([preds_table, loc_preds_table])
            
    return preds_table

# IV. Decalre Variables:

In [3]:
# i. model name:
m_id, n_jobs = 'model_3_0', 7
# ii. dates:
start_date, end_date =\
    pd.datetime(2017, 6, 13).date(), pd.datetime(2017, 6, 14).date()
# iii. pwds:
raw_data_pwd =\
    '/Users/meghavalsan/Dropbox (AutoGrid)/sqlfiles/'
meta_pwd =\
    '/Users/meghavalsan/megha_github/model3files/feedermeta/'
model_pwd =\
    '/Users/meghavalsan/megha_github/model3files/modelpkl/model_v_3_0.pkl'
config_pwd =\
    '/Users/meghavalsan/megha_github/model3files/config/'
dataset_config_pwd =\
    config_pwd + 'pam_3_0_dataset.yaml'
anomaly_map_pwd =\
    config_pwd + 'pam_3_0_anoms_anomaly_map.yaml'
alert_config_pwd =\
    config_pwd + 'pam_3_0_alert.yaml'

# V. Alerts Generation:

In [4]:
# i. initiate class:
june_13_14_2017_alerts = BatchAlerts(
    n_jobs, start_date, end_date,
    raw_data_pwd, meta_pwd)

In [5]:
# ii. load data:
june_13_14_2017_alerts.load_data()

/Users/meghavalsan/megha_github/pammodel3env/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2881: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [6]:
# iii. process anomalies:
june_13_14_2017_alerts.generates_anomalies()

Launching 7 jobs for scada data!

[Parallel(n_jobs=7)]: Done   1 out of   7 | elapsed:   17.5s remaining:  1.8min
[Parallel(n_jobs=7)]: Done   7 out of   7 | elapsed:   19.1s finished

Launching 7 jobs for ami data!
ERROR! fdr 208864 does not have meta data info!
ERROR! fdr 800831 does not have meta data info!
ERROR! fdr 813135 does not have meta data info!
ERROR! fdr 408668 does not have meta data info!
ERROR! fdr 814131 does not have meta data info!
ERROR! fdr 208167 does not have meta data info!
ERROR! fdr 811432 does not have meta data info!
ERROR! fdr 400239 does not have meta data info!
ERROR! fdr 808163 does not have meta data info!
ERROR! fdr 109035 does not have meta data info!
ERROR! fdr 807338 does not have meta data info!
ERROR! fdr 108434 does not have meta data info!
ERROR! fdr 811364 does not have meta data info!
ERROR! fdr 800846 does not have meta data info!
ERROR! fdr 812363 does not have meta data info!
ERROR! fdr 507165 does not have meta data info!
ERROR! fdr 408566 does not have meta data info!
ERROR! fdr 802138 does not have meta data info!
ERROR! fdr 408565 does not have meta data info!
ERROR! fdr 403238 does not have meta data info!

[Parallel(n_jobs=7)]: Done   1 out of   7 | elapsed:   26.2s remaining:  2.6min

ERROR! fdr 401763 does not have meta data info!
ERROR! fdr 409863 does not have meta data info!
ERROR! fdr 104432 does not have meta data info!
ERROR! fdr 410033 does not have meta data info!
ERROR! fdr 400665 does not have meta data info!
ERROR! fdr 508465 does not have meta data info!
ERROR! fdr 108963 does not have meta data info!
ERROR! fdr 813139 does not have meta data info!
ERROR! fdr 204634 does not have meta data info!
ERROR! fdr 403631 does not have meta data info!
ERROR! fdr 412261 does not have meta data info!
ERROR! fdr 800135 does not have meta data info!
ERROR! fdr 704070 does not have meta data info!
ERROR! fdr 505861 does not have meta data info!
ERROR! fdr 800336 does not have meta data info!
ERROR! fdr 812165 does not have meta data info!
ERROR! fdr 402731 does not have meta data info!
ERROR! fdr 709161 does not have meta data info!
ERROR! fdr 407335 does not have meta data info!
ERROR! fdr 811938 does not have meta data info!
ERROR! fdr 412262 does not have meta data info!
ERROR! fdr 814132 does not have meta data info!
ERROR! fdr 813136 does not have meta data info!
ERROR! fdr 203540 does not have meta data info!
ERROR! fdr 703037 does not have meta data info!
ERROR! fdr 807736 does not have meta data info!
ERROR! fdr 508163 does not have meta data info!
ERROR! fdr 209765 does not have meta data info!
ERROR! fdr 707864 does not have meta data info!
ERROR! fdr 410032 does not have meta data info!
ERROR! fdr 804339 does not have meta data info!
ERROR! fdr 701437 does not have meta data info!
ERROR! fdr 508263 does not have meta data info!
ERROR! fdr 504764 does not have meta data info!
ERROR! fdr 207064 does not have meta data info!
ERROR! fdr 501436 does not have meta data info!
ERROR! fdr 507365 does not have meta data info!
ERROR! fdr 809338 does not have meta data info!

[Parallel(n_jobs=7)]: Done   7 out of   7 | elapsed:   52.4s finished

Launching 7 jobs for edna data!

[Parallel(n_jobs=7)]: Done   1 out of   7 | elapsed:  9.5min remaining: 56.8min
[Parallel(n_jobs=7)]: Done   7 out of   7 | elapsed: 39.1min finished

In [7]:
# iv. generate alerts:
june_13_14_2017_alerts.generates_alerts(
        m_id, model_pwd,
        dataset_config_pwd,
        anomaly_map_pwd, alert_config_pwd
    )

/Users/meghavalsan/megha_github/pammodel3env/lib/python2.7/site-packages/pandas/core/generic.py:2387: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
/Users/meghavalsan/megha_github/pammodel3env/lib/python2.7/site-packages/pandas/core/generic.py:2387: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
/Users/meghavalsan/megha_github/pammodel3env/lib/python2.7/site-packages/pandas/core/generic.py:2387: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
/Users/meghavalsan/megha_github/pammodel3env/lib/python2.7/site-packages/pandas/core/generic.py:2387: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
/Users/meghavalsan/megha_github/pammodel3env/lib/python2.7/site-packages/pandas/core/generic.py:2387: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
/Users/meghavalsan/megha_github/pammodel3env/lib/python2.7/site-packages/pandas/core/generic.py:2387: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
/Users/meghavalsan/megha_github/pammodel3env/lib/python2.7/site-packages/pandas/core/generic.py:2387: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
[Parallel(n_jobs=7)]: Done   1 out of   7 | elapsed:  5.1min remaining: 30.4min
[Parallel(n_jobs=7)]: Done   7 out of   7 | elapsed:  5.3min finished

In [8]:
# v. pkl results:
pickle.dump(june_13_14_2017_alerts.alerts_dict, open('jun_13_14_2017_alerts_dict_m_3_0.pkl', 'wb'))
pickle.dump(june_13_14_2017_alerts.anoms_df, open('jun_13_14_2017_anoms_df_m_3_0.pkl', 'wb'))

# VI. Alerts EDA:

## June 13 ~ 14, 2017:

In [9]:
june_13_14_2017_preds_df =\
    combine_preds_df(june_13_14_2017_alerts.alerts_dict)

In [76]:
june_13_14_2017_preds_df.shape

(1116, 11)

In [10]:
june_13_14_2017_preds_df['FEEDER'].unique()

array(['706364', '706365', '706367', '706361', '706362', '706363',
       '409862', '706166', '706167', '706164', '706162', '706161',
       '503633', '503632', '503631', '503634', '503639', '503638',
       '504761', '504762', '504763', '508362', '806532', '505663',
       '505661', '201433', '802136', '201431', '201437', '201434',
       '201435', '505363', '505362', '505365', '506762', '505561',
       '505563', '506761', '800936', '506263', '506262', '506261',
       '500764', '301562', '500766', '500763', '506465', '506464',
       '500768', '506463', '506462', '700237', '506861', '506862',
       '701031', '204064', '204065', '204061', '701038', '700139',
       '101931', '703543', '703542', '703540', '409633', '707863',
       '204364', '810366', '808731', '808732', '401833', '204264',
       '703537', '203541', '204263', '703431', '407164', '407165',
       '407166', '407167', '407162', '306134', '506035', '306133',
       '506031', '411031', '411033', '202134', '202135', '106531',
       '804232', '202033', '502461', '811063', '502463', '502462',
       '502464', '811065', '811562', '811561', '502637', '407861',
       '407862', '407865', '207862', '207861', '503435', '503434',
       '508363', '201736', '807435', '807432', '807433', '203533',
       '703232', '405032', '803134', '700443', '102436', '809668',
       '809665', '809664', '809661', '809663', '700537', '808837',
       '808836', '808835', '808834', '808833', '808832', '700438',
       '700439', '700437', '700432', '700433', '700431', '401631',
       '703631', '703632', '703634', '703636', '102365', '102362',
       '102361', '800533', '408664', '408665', '808331', '808332',
       '808333', '508863', '508862', '508861', '804334', '804335',
       '804336', '803437', '803434', '803435', '300964', '803438',
       '803439', '804338', '300962', '800446', '402931', '800445',
       '402936', '402937', '800448', '808831', '700834', '700933',
       '700932', '700934', '804633', '804635', '804634', '508162',
       '508161', '703835', '105832', '105831', '405934', '705466',
       '705467', '705464', '700941', '504369', '504364', '504365',
       '504366', '504367', '504361', '504363', '706261', '507261',
       '507262', '507263', '507264', '507266', '405633', '405631',
       '405636', '405637', '405634', '405635', '203331', '401761',
       '807831', '504661', '508261', '508262', '706863', '706862',
       '706861', '802133', '807735', '807734', '505761', '807161',
       '807162', '807163', '807165', '200261', '200262', '504665',
       '402632', '402631', '409436', '706964', '503862', '503863',
       '704762', '506461', '704766', '704764', '704765', '700731',
       '700732', '700737', '700736', '700738', '401534', '801140',
       '810562', '703731', '703733', '700234', '205363', '700236',
       '205361', '700231', '208861', '501234', '501237', '809434',
       '809433', '702737', '203535', '706465', '203536', '706463',
       '501536', '501537', '501534', '501535', '501532', '501533',
       '501531', '810063', '810062', '501433', '501432', '501538',
       '400661', '507863', '808267', '507562', '402536', '402533',
       '204062', '402538', '801135', '508864', '801134', '401034',
       '401035', '401036', '208165', '401032', '401033', '108362',
       '108363', '208161', '502531', '801136', '801139', '308061',
       '308063', '308064', '800447', '811564', '209764', '801934',
       '800440', '800441', '410231', '406866', '401031', '703132',
       '703133', '703032', '100934', '105132', '105133', '400934',
       '506037', '412164', '202131', '301331', '210133', '210132',
       '501833', '101463', '101464', '101466', '702535', '702534',
       '708561', '800232', '801634', '704568', '704561', '704562',
       '704563', '704564', '704565', '704566', '406932', '800734',
       '800737', '804133', '412161', '804134', '802232', '802231',
       '506768', '506769', '506763', '506764', '408564', '806732',
       '707861', '408761', '808734', '808270', '400931', '506163',
       '506364', '506362', '506363', '505465', '508061', '502938',
       '502936', '502935', '804340', '703536', '709431', '203931',
       '502163', '508063', '508062', '705763', '705762', '705765',
       '507466', '705768', '507462', '402634', '406231', '406237',
       '406235', '406234', '507062', '507063', '507061', '507064',
       '507065', '805836', '503765', '503766', '503761', '411563',
       '507364', '507361', '507363', '507362', '100532', '206931',
       '503264', '503265', '503261', '503263', '100839', '100833',
       '100834', '100836', '100334', '100333', '100332', '507962',
       '507961', '100236', '406063', '406061', '100232', '100233',
       '406064', '405269', '405268', '405261', '405263', '405265',
       '405266', '700636', '809932', '809939', '807961', '807962',
       '702438', '702431', '702432', '702433', '704663', '702435',
       '702436', '702437', '405467', '104431', '405465', '405461',
       '106363', '106361', '305232', '406935', '406936', '406937',
       '406931', '406933', '306132', '404134', '404132', '404133',
       '702434', '404034', '203035', '404031', '802532', '802533',
       '701932', '108961', '403235', '403232', '701043', '802835',
       '802834', '802837', '405464', '802833', '802832', '400434',
       '700635', '808169', '702938', '702936', '808165', '808164',
       '400932', '808733', '305231', '406934', '410761', '700240',
       '405863', '405865', '405869', '405868', '705535', '706062',
       '706064', '400533', '300631', '505864', '505862', '804239',
       '403634', '100131', '100133', '100132', '100135', '100134',
       '100137', '100136', '100139', '100138', '706263', '507265',
       '301135', '301133', '209862', '409962', '409963', '409961',
       '811061', '208163', '811064', '501134', '501135', '409361',
       '100938', '701839', '701831', '701832', '802233', '802235',
       '802234', '408763', '806733', '806736', '806737', '806734',
       '408764', '505461', '505462', '505463', '505464', '408164',
       '408166', '100933', '408162', '404734', '203933', '203935',
       '404731', '404732', '411562', '411561', '404036', '805333',
       '207863', '805331', '805337', '805336', '805335', '105131',
       '802240', '200431', '200433', '200432', '200434', '203631',
       '203635', '412061', '401764', '506667', '506666', '506665',
       '506664', '506662', '504966', '504835', '504962', '102033',
       '107632', '107631', '107633', '702832', '707662', '707663',
       '707661', '403033', '403031', '402763', '403034', '403038',
       '501435', '502065', '502064', '502061', '507764', '502063',
       '503566', '503565', '503564', '503563', '503562', '503561',
       '503569', '503568', '101635', '507163', '507162', '507161',
       '101634', '502562', '503969', '503968', '503963', '503962',
       '706066', '503967', '503966', '703961', '703962', '812162',
       '807733', '207361', '207362', '207363', '812063', '205362',
       '812061', '406763', '406762', '406764', '406767', '701931',
       '701933', '803132', '500933', '500932', '802038', '802037',
       '802036', '500438', '500432', '500434', '500436', '807633',
       '807634', '807635', '806336', '806334', '802734', '802735',
       '802732', '802731', '408762', '806340', '205434', '406864',
       '201931', '400935', '809761', '809763', '809766', '102634',
       '102631', '704763', '704761', '701233', '701232', '701231',
       '408765', '400436', '700633', '400433', '400431', '700637',
       '700639', '400536', '400537', '400534', '301463', '301461',
       '808161', '102032', '209863', '808162', '209864', '208634',
       '208632', '208631', '502161', '504967', '504964', '504965',
       '504963', '504961', '504968', '504969', '507761', '502067',
       '709261', '709262', '709263', '505961', '505963', '505962',
       '500835', '500837', '500831', '500832', '800733', '504431',
       '504432', '504433'], dtype=object)

In [11]:
multi_row = []

for fdr in june_13_14_2017_preds_df['FEEDER'].unique():
    loc_df =\
        june_13_14_2017_preds_df.loc[june_13_14_2017_preds_df['FEEDER']==fdr]
    if loc_df.shape[0] > 2:
        multi_row.append(fdr)

In [73]:
new_fr1=pd.DataFrame()
for fdr in june_13_14_2017_preds_df['FEEDER'].unique():
    loc_df =\
        june_13_14_2017_preds_df.loc[june_13_14_2017_preds_df['FEEDER']==fdr]
    if loc_df.shape[0] > 1:
        for d in loc_df['TIMESTAMP'].dt.date.unique():
            ld_df=loc_df.loc[loc_df['TIMESTAMP'].dt.date==d]
            if ld_df.shape[0] > 1:
                new_fr1=new_fr1.append(ld_df.tail(1))
            else:
                new_fr1=new_fr1.append(ld_df)
    else:
        new_fr1=new_fr1.append(loc_df)

In [74]:
new_fr1

,FEEDER,TIMESTAMP,PROB,ALERT,TIER,LG_PD_10_24,ZERO_VOLTAGE_V3_24,AFS_GROUND_ALARM_24,FDRHD_DE_ENERGIZED_24,ZERO_POWER_V3_24,INTELI_PH_ALARM_24
0,706364,2017-06-14 18:59:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,706365,2017-06-13 13:46:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
1,706365,2017-06-14 18:47:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,706367,2017-06-14 18:59:00+00:00,0.058489,Yellow,0,1,0,0,0,0,3
0,706361,2017-06-13 13:46:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,706362,2017-06-14 18:59:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,706363,2017-06-13 13:46:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
1,706363,2017-06-14 18:47:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,409862,2017-06-14 11:55:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,706166,2017-06-14 14:08:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,706167,2017-06-14 14:08:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,706164,2017-06-14 14:08:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,706162,2017-06-14 14:08:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
1,706161,2017-06-14 14:50:00+00:00,0.059397,Yellow,0,0,0,2,0,0,0
0,503633,2017-06-14 16:46:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,503632,2017-06-13 20:53:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,503631,2017-06-14 16:46:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,503634,2017-06-14 16:46:00+00:00,0.059397,Yellow,0,1,0,0,1,0,0
0,503639,2017-06-13 20:53:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,503638,2017-06-13 20:53:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
2,504761,2017-06-14 17:02:00+00:00,0.062071,Yellow,0,3,0,0,0,0,0
0,504762,2017-06-13 12:03:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
1,504762,2017-06-14 16:55:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,504763,2017-06-13 12:03:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
2,504763,2017-06-14 16:55:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
0,508362,2017-06-12 16:27:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
1,508362,2017-06-13 20:15:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,806532,2017-06-13 12:43:00+00:00,0.059565,Yellow,0,0,0,0,0,1,0
0,505663,2017-06-13 21:15:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,505661,2017-06-13 21:15:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1,504965,2017-06-12 18:05:00+00:00,0.059397,Yellow,0,1,0,1,0,0,2
2,504965,2017-06-13 19:53:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
3,504965,2017-06-14 15:04:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
2,504963,2017-06-12 21:37:00+00:00,0.061291,Yellow,0,2,0,1,0,0,2
3,504963,2017-06-14 15:04:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,504961,2017-06-13 19:53:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
4,504961,2017-06-14 18:30:00+00:00,0.059397,Yellow,0,1,0,6,0,0,0
0,504968,2017-06-12 18:00:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
3,504968,2017-06-14 15:40:00+00:00,0.058489,Yellow,0,1,0,2,0,0,3
0,504969,2017-06-12 18:00:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
1,504969,2017-06-14 15:04:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,507761,2017-06-12 17:40:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,502067,2017-06-12 18:59:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,709261,2017-06-13 09:02:00+00:00,0.059565,Yellow,0,0,0,0,0,1,0
0,709262,2017-06-13 09:02:00+00:00,0.059565,Yellow,0,0,0,0,0,1,0
0,709263,2017-06-13 09:02:00+00:00,0.058582,Yellow,0,0,2,0,0,0,0
0,505961,2017-06-12 17:00:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
6,505961,2017-06-13 23:08:00+00:00,0.063498,Yellow,0,6,0,0,0,0,0
7,505961,2017-06-14 17:38:00+00:00,0.064502,Yellow,0,7,0,0,0,0,0
0,505963,2017-06-13 19:20:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,505962,2017-06-13 19:17:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,500835,2017-06-13 21:33:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,500837,2017-06-13 21:33:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
1,500831,2017-06-13 21:33:00+00:00,0.059565,Yellow,0,1,3,0,2,1,0
0,500832,2017-06-13 21:33:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,800733,2017-06-12 21:45:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,504431,2017-06-12 21:03:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
0,504432,2017-06-12 20:46:00+00:00,0.059397,Yellow,0,1,0,0,1,0,0
0,504433,2017-06-12 21:05:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
1,504433,2017-06-14 15:24:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0

In [80]:
len(multi_row)

94

In [69]:
new_fr=pd.DataFrame()
for fdr in multi_row:
    loc_df =\
        june_13_14_2017_preds_df.loc[june_13_14_2017_preds_df['FEEDER']==fdr]
    for d in loc_df['TIMESTAMP'].dt.date.unique():
        ld_df=loc_df.loc[loc_df['TIMESTAMP'].dt.date==d]
        if ld_df.shape[0] > 1:
            new_fr=new_fr.append(ld_df.tail(1))
        else:
            new_fr=new_fr.append(ld_df)

In [70]:
new_fr=new_fr.reset_index()
new_fr.drop(['index'], axis=1, inplace=True)
new_fr

,FEEDER,TIMESTAMP,PROB,ALERT,TIER,LG_PD_10_24,ZERO_VOLTAGE_V3_24,AFS_GROUND_ALARM_24,FDRHD_DE_ENERGIZED_24,ZERO_POWER_V3_24,INTELI_PH_ALARM_24
0,504761,2017-06-14 17:02:00+00:00,0.062071,Yellow,0,3,0,0,0,0,0
1,504763,2017-06-13 12:03:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
2,504763,2017-06-14 16:55:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
3,506464,2017-06-12 23:55:00+00:00,0.060957,Yellow,0,2,0,4,0,0,0
4,506464,2017-06-13 21:25:00+00:00,0.060957,Yellow,0,2,0,6,0,0,0
5,506462,2017-06-12 23:14:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
6,506462,2017-06-13 20:41:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
7,506861,2017-06-13 21:30:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
8,506861,2017-06-14 17:46:00+00:00,0.062071,Yellow,0,3,0,0,0,0,0
9,506862,2017-06-13 21:36:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
10,506862,2017-06-14 16:57:00+00:00,0.060957,Yellow,0,2,0,0,1,0,0
11,808731,2017-06-13 21:50:00+00:00,0.060957,Yellow,0,2,0,0,0,0,1
12,502461,2017-06-14 06:13:00+00:00,0.062071,Yellow,0,3,0,0,0,0,0
13,502463,2017-06-13 19:22:00+00:00,0.065675,Yellow,0,4,0,0,0,0,3
14,502463,2017-06-14 16:50:00+00:00,0.064502,Yellow,0,8,0,0,0,0,3
15,207861,2017-06-12 19:30:00+00:00,0.059397,Yellow,0,1,0,2,1,0,0
16,809665,2017-06-12 09:20:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
17,809665,2017-06-14 15:54:00+00:00,0.059397,Yellow,0,0,0,0,1,0,0
18,809664,2017-06-12 17:56:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
19,809664,2017-06-14 01:18:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
20,808835,2017-06-13 21:20:00+00:00,0.059565,Yellow,0,1,3,0,0,1,0
21,808835,2017-06-14 15:20:00+00:00,0.061402,Yellow,0,2,3,0,0,1,0
22,808834,2017-06-13 21:20:00+00:00,0.059565,Yellow,0,0,3,0,0,1,0
23,808834,2017-06-14 15:20:00+00:00,0.061402,Yellow,0,2,3,0,0,1,0
24,808832,2017-06-13 21:20:00+00:00,0.059565,Yellow,0,0,3,0,0,1,0
25,808832,2017-06-14 15:20:00+00:00,0.061738,Yellow,0,2,3,0,1,1,2
26,102365,2017-06-12 05:38:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
27,102365,2017-06-13 14:31:00+00:00,0.059565,Yellow,0,1,3,0,1,1,0
28,408664,2017-06-13 15:45:00+00:00,0.059397,Yellow,0,1,0,2,0,0,0
29,408664,2017-06-14 17:53:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
117,503562,2017-06-14 17:00:00+00:00,0.059397,Yellow,0,1,0,0,0,0,1
118,503568,2017-06-12 18:07:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
119,503568,2017-06-14 17:00:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
120,507162,2017-06-14 19:10:00+00:00,0.063498,Yellow,0,5,0,0,0,0,0
121,507161,2017-06-14 20:47:00+00:00,0.065675,Yellow,0,3,0,0,0,0,7
122,503967,2017-06-14 17:05:00+00:00,0.059397,Yellow,0,1,0,4,0,0,0
123,207361,2017-06-13 16:03:00+00:00,0.062153,Yellow,0,4,3,0,1,1,0
124,207363,2017-06-13 16:02:00+00:00,0.061201,Yellow,0,4,0,0,0,0,1
125,406864,2017-06-12 14:21:00+00:00,0.059397,Yellow,0,0,0,4,0,0,0
126,700633,2017-06-13 18:51:00+00:00,0.062071,Yellow,0,3,0,0,0,0,0
127,400433,2017-06-13 21:37:00+00:00,0.059565,Yellow,0,1,3,0,2,1,0
128,400433,2017-06-14 11:30:00+00:00,0.061402,Yellow,0,2,3,0,2,1,0
129,301463,2017-06-13 09:40:00+00:00,0.059397,Yellow,0,1,0,2,0,0,0
130,301463,2017-06-14 19:22:00+00:00,0.062153,Yellow,0,4,0,0,0,0,0
131,301461,2017-06-13 08:56:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
132,301461,2017-06-14 19:22:00+00:00,0.062153,Yellow,0,4,0,0,0,0,0
133,504967,2017-06-12 23:45:00+00:00,0.059397,Yellow,0,1,0,2,0,0,1
134,504967,2017-06-14 15:25:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
135,504965,2017-06-12 18:05:00+00:00,0.059397,Yellow,0,1,0,1,0,0,2
136,504965,2017-06-13 19:53:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
137,504965,2017-06-14 15:04:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0
138,504963,2017-06-12 21:37:00+00:00,0.061291,Yellow,0,2,0,1,0,0,2
139,504963,2017-06-14 15:04:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
140,504961,2017-06-13 19:53:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
141,504961,2017-06-14 18:30:00+00:00,0.059397,Yellow,0,1,0,6,0,0,0
142,504968,2017-06-12 18:00:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
143,504968,2017-06-14 15:40:00+00:00,0.058489,Yellow,0,1,0,2,0,0,3
144,505961,2017-06-12 17:00:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
145,505961,2017-06-13 23:08:00+00:00,0.063498,Yellow,0,6,0,0,0,0,0
146,505961,2017-06-14 17:38:00+00:00,0.064502,Yellow,0,7,0,0,0,0,0

In [14]:
june_13_14_2017_preds_df.loc[june_13_14_2017_preds_df['FEEDER']=='504763']

,FEEDER,TIMESTAMP,PROB,ALERT,TIER,LG_PD_10_24,ZERO_VOLTAGE_V3_24,AFS_GROUND_ALARM_24,FDRHD_DE_ENERGIZED_24,ZERO_POWER_V3_24,INTELI_PH_ALARM_24
0,504763,2017-06-13 12:03:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
1,504763,2017-06-14 16:38:00+00:00,0.059397,Yellow,0,1,0,0,0,0,0
2,504763,2017-06-14 16:55:00+00:00,0.060957,Yellow,0,2,0,0,0,0,0

## June 15 ~ 16, 2017:

## June 17 ~ 18, 2017:

## June 19 ~ 20, 2017: